name: build and test

on: [push, pull_request]

jobs:

  build:
    name: build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
          POSTGRES_PORT: 5432
          POSTGRES_USER: test
        ports:
          - 5432:5432
        # Health check to wait until postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test package
      run: go test -v .

    - name: Test SQLite
      run: go test -v ./db-test/

    - name: Test PostgreSQL via pgx
      run: go test -v ./db-test/ --db-driver pgx --db-dsn "host=localhost port=5432 user=test password=test dbname=test sslmode=disable"